create table public._users
(
    id           bigserial
        constraint users_pk
            primary key,
    username     varchar(50),
    email        varchar(50),
    password     varchar(120),
    name         varchar(50),
    surname      varchar(50),
    birth_date   timestamp,
    phone_number varchar,
    language     varchar
);

create unique index users_email_uindex
    on public._users (email);

create unique index users_id_uindex
    on public._users (id);

create unique index users_username_uindex
    on public._users (username);

create table public._roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(50)
);

create table public._user_roles
(
    user_id bigint  not null
        constraint _users_roles_pk
            references public._users,
    role_id integer not null
        constraint _users_roles_role_id_fk
            references public._roles,
    primary key (user_id, role_id)
);

create table public._category
(
    id          bigint generated by default as identity primary key,
    description varchar(255),
    img         varchar(255),
    name        varchar(255) unique
);

create table public._city
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table public._tournament
(
    id           bigint generated by default as identity primary key,
    description  text,
    end_date     timestamp,
    name         varchar(30),
    prize_fund   integer,
    start_date   timestamp,
    created_at   timestamp default CURRENT_TIMESTAMP,
    location     varchar,
    subtitle     varchar not null,
    status       varchar,
    category_id  integer not null
        constraint _category_id_fk
            references public._category,
    organizer_id bigint
        constraint _user_id_fk
            references public._users,
    city_id      integer
        constraint _city_id_fk
            references public._city
);


create table public._user_tournament
(
    id            bigint generated by default as identity primary key,
    tournament_id bigint not null
        constraint _tournament_id_fk
            references public._tournament,
    user_id       bigint not null
        constraint _users_id_fk
            references public._users
);

INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_USER');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_SUBJECT_TEACHER');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_MODERATOR');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_STUDENT');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_ADMIN');


