create table _users
(
    id           bigserial
        constraint users_pk
            primary key,
    username     varchar(50),
    email        varchar(50),
    "password"   varchar(120),
    "name"       varchar(50),
    surname      varchar(50),
    birth_date   timestamp,
    phone_number varchar,
    "language"   varchar
);
create unique index users_email_uindex
    on _users (email);

create unique index users_id_uindex
    on _users (id);

create unique index users_username_uindex
    on _users (username);

create table _roles
(
    id   bigint generated by default as identity primary key,
    name varchar(50)
);

create table _user_roles
(
    user_id bigint  not null
        constraint _users_roles_pk
            references
                _users,
    role_id integer not null
        constraint _users_roles_role_id_fk
            references _roles,
    primary key (user_id, role_id)
);

INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_USER');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_SUBJECT_TEACHER');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_MODERATOR');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_STUDENT');
INSERT INTO _roles (id, name)
VALUES (DEFAULT, 'ROLE_ADMIN');
