server:
  port: 8086

spring:
  application:
    name: db-struct
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5436}/${DB_NAME:sportify-db}
    username: ${DB_USER:adilet}
    password: ${DB_PASSWORD:050302}
  liquibase:
    change-log: db/changeLog.xml
