server:
  port: 8083
  servlet:
    context-path: /administration

spring:
  application:
    name: administration
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5436}/${DB_NAME:sportify-db}
    username: ${DB_USER:adilet}
    password: ${DB_PASSWORD:050302}
  jpa:
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
